#!/bin/bash

echo "Running pre-commit hook"

PAGE_LISTING=pages/page-listing

# Clear the page listing
> ${PAGE_LISTING}

for filename in pages/markdown/**/*.md; do
    [ -e "$filename" ] || continue
    echo "Indexing page $path"
    sed -r -n -e 's/\$summary\s*=\s*(.+)/&/p' -e 's/\$title\s*=\s*(.+)/&/p' \
    -e 's/\$date\s*=\s*(.*)/&/p' ${filename} >> ${PAGE_LISTING}
    echo "\$path=$filename" >> ${PAGE_LISTING}
    # New line for clarity
    echo "" >> ${PAGE_LISTING}
done

git add $PAGE_LISTING
exit $?


